# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Stories',     url: 'stories'}
- {name: 'Field Notes',  url: 'notes'}
- {name: 'FYI',         url: 'fyi'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/radlakha'}
- {icon: 'facebook', link:   'https://www.facebook.com/radlakha'}
- {icon: 'instagram', link:  'https://instagram.com/radlakha'}
- {icon: 'envelope', link:   'mailto:raman .githubpages@adlakhas.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
